CC = gcc
INCLUDE_PATHS =
LIBRARY_PATHS =
COMPILER_FLAGS = -Wall -Wextra -pedantic
LINKER_FLAGS =

part2: part2.c
	$(CC) part2.c $(INCLUDE_PATHS) $(LIBRARY_PATHS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o part2

all: part2

clean:
	rm -f part2
