OBJS = part1.c
CC = gcc
INCLUDE_PATHS =
LIBRARY_PATHS =
COMPILER_FLAGS = -Wall -Wextra -pedantic
LINKER_FLAGS =
OBJ_NAME = part1

part1: part1.c
	$(CC) part1.c $(INCLUDE_PATHS) $(LIBRARY_PATHS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o part1

part2: part2.c
	$(CC) part2.c $(INCLUDE_PATHS) $(LIBRARY_PATHS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o part2

clean:
	rm -f part1 part2
